### ISSUE TITLE
[Bug] Internal error after redeclaration of variable

### ISSUE THREAD

**Issue by Luna-Klatzer** [Kipper-Lang/Kipper#462]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I am following the documentation's guide

- [X] I have read the documentation

### This issue exists in the latest version

- [X] I am using the latest version

### Current Behavior

Using the following code, the compiler generates an `InternalError` reporting a failure in the resolution of the internal scope declaration:

```ts
var name: str = "Luna";
var age: num = 20;

var name: str = "Luna";
var age: num = 20;
```

The resulting error:

```bash
ERROR Compilation error - Traceback:
File '/home/luna/data/WebstormProjects/Kipper/test.kip', line 3, col 0:
  var name: str = "Luna";
  ^^^^^^^^^^^^^^^^^^^^^^ 
IdentifierError: Redeclaration of variable 'name'. 
FATAL Failed to compile 'test.kip'. 
FATAL Encountered unexpected internal error: 
InternalError: Failed to determine the declaration context for a declaration. Most likely the semantic analysis failed or the property was accessed too early during semantic analysis. - Report this bug to the developer using the traceback!
    at VariableDeclaration.getScopeDeclaration (/home/luna/.local/share/pnpm/global/5/.pnpm/@kipper+core@0.10.1/node_modules/@kipper/core/lib/compiler/ast/nodes/definitions.js:27:19)
    at VariableDeclaration.getScopeDeclaration (/home/luna/.local/share/pnpm/global/5/.pnpm/@kipper+core@0.10.1/node_modules/@kipper/core/lib/compiler/ast/nodes/definitions.js:186:22)
    at VariableDeclaration.<anonymous> (/home/luna/.local/share/pnpm/global/5/.pnpm/@kipper+core@0.10.1/node_modules/@kipper/core/lib/compiler/ast/nodes/definitions.js:227:78)
    at Generator.next (<anonymous>)
    at /home/luna/.local/share/pnpm/global/5/.pnpm/tslib@2.4.1/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/home/luna/.local/share/pnpm/global/5/.pnpm/tslib@2.4.1/node_modules/tslib/tslib.js:114:16)
    at VariableDeclaration.primarySemanticTypeChecking (/home/luna/.local/share/pnpm/global/5/.pnpm/@kipper+core@0.10.1/node_modules/@kipper/core/lib/compiler/ast/nodes/definitions.js:218:24)
    at VariableDeclaration.<anonymous> (/home/luna/.local/share/pnpm/global/5/.pnpm/@kipper+core@0.10.1/node_modules/@kipper/core/lib/compiler/ast/analysable-ast-node.js:103:32)
    at Generator.next (<anonymous>)
```

To simply the reproduction case, you can simply write:

```ts
var name: str = "Luna";
var name: str = "Luna";
```

### Expected Behavior

The compiler should only return the redeclaration errors and not the internal error.

### Steps To Reproduce

1. Define a variable with a value assigned of any type.
2. Create another variable definition with a value of the same type.
3. For example:
    ```ts
    var name: str = "Luna";
    var name: str = "Luna";
    ```

### Environment

- Kipper: 0.10.1
- Environment: Node.js v18.15.0
- Operating System: Arch Linux with Kernel 6.1.27-1-lts

**Comment by Luna-Klatzer** [comment]
Fixed by:
- #463 and released in `v0.10.2` with #474.
- #464 and released in `v0.11.0-alpha.0` with #473.
